### PR TITLE
Adding link to mailing list

### PR DESCRIPTION
**Pull request by csgillespie**

### CODE REVIEW

**Comment by csgillespie** [comment]
@Rosalita Any idea why the link isn't showing on the website?

**Comment by Rosalita** [comment]
will git clone it now and take a look

**Comment by Rosalita** [comment]
@csgillespie It looked like the .rmd files had change but new html files had not been generated by running rmarkdown::render_site()

I should have fixed this now. 

To update your branch to the new head of rnortheast.github.io
1) Check if you have https://github.com/RNorthEast/rnortheast.github.io.git as a remote by typing:
git remote -v 
2) if its not on the list type: 
git remote add parent https://github.com/RNorthEast/rnortheast.github.io.git
if it is on the list use the name listed instead of "parent" for the following steps
3) Type:
git fetch parent
4) Type
git reset --hard parent/master
5) Type:
git push --force

Your local branch will now match the remote at rnortheast.github.io

**Comment by csgillespie** [comment]
Thanks - I always forget that.

**Comment by Rosalita** [comment]
Feel free to endorse my R / Rstudio / Git skills on LinkedIn ;)

**Pull request merged**
